# Generated by Django 5.1 on 2024-09-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Category',
            new_name='category',
        ),
    ]
